image: python:3.10

pipelines:
  default:
    - step:
        name: Install Dependencies
        caches:
          - pip
        script:
          - export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python3.10/site-packages:/opt/atlassian/pipelines/agent/build/Code
          - pip install -r Code/requirements.txt
          - pip install coverage
          - pip install unittest-xml-reporting
    - step:
        name: Run migrations
        script: 
          - python Code/manage.py migrate
    - step: 
        name: Run tests - regression testing
        script:
          - TEST_OUTPUT_DIRECTORY="test-results" coverage run --source="./Code" Code/manage.py test accounts.tests customers.tests salons.tests 
          - coverage report
          - coverage html 
          - coverage xml

        artifacts:
          - htmlcov/**
          - coverage.xml
          - test-results/test-report.xml
        # test:
        #   reports:
        #     junit: test-results/test-report.xml

definitions:
  caches:
    pip: ~/.cache/pip
