image: python:3.11

pipelines:
  default:
    - step: 
        name: Run tests - regression testing
        caches:
          - pip
        script:
          - pip install -r Code/requirements.txt
          - pip install coverage

          - coverage run --source="." Code/manage.py test #test
          - coverage report
          - coverage html 
          - coverage xml

        artifacts:
          - htmlcov/**
          - ./test-reports/coverage.xml

definitions:
  caches:
    pip: ~/.cache/pip
