image: python:3.11

pipelines:
  default:
    - step: 
        name: Run tests - regression testing
        caches:
          - pip
        script:
          - pip install -r Code/requirements.txt
          - pip install coverage
          - pip install pytest pytest-django

          - coverage run --source="." Code/manage.py test --testrunner=pytest_django.runner.PytestDjangoTestRunner --junitxml=test-results/test-report.xml #test
          - coverage report
          - coverage html 
          - coverage xml

        artifacts:
          - htmlcov/**
          - coverage.xml
          - test-results/test-report.xml

definitions:
  caches:
    pip: ~/.cache/pip
