# Generated by Django 5.1.1 on 2024-09-15 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalonAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SalonInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salon_name', models.CharField(max_length=255)),
                ('salon_photo', models.ImageField(blank=True, null=True, upload_to='salon_photos/')),
                ('salon_openingtime', models.TimeField()),
                ('salon_closingtime', models.TimeField()),
                ('happyhour_times', models.CharField(max_length=255)),
                ('happyhour_days', models.CharField(max_length=255)),
                ('happyhour_discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('salon_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='salons.salonaddress')),
            ],
        ),
        migrations.CreateModel(
            name='SalonOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('salon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='salons.saloninfo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalonService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.DurationField()),
                ('description', models.TextField(blank=True, null=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salons.saloninfo')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salons.service')),
            ],
        ),
    ]
