# Generated by Django 5.1 on 2024-08-31 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_type',
        ),
        migrations.AddField(
            model_name='users',
            name='type',
            field=models.CharField(choices=[('admin', 'admin'), ('business', 'business'), ('customer', 'customer')], default='customer', max_length=255),
        ),
    ]
