# Generated by Django 5.1 on 2024-09-19 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_users_user_type_users_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinfo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='saloninfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='users',
            name='address',
        ),
        migrations.RemoveField(
            model_name='saloninfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
        migrations.DeleteModel(
            name='CustomerInfo',
        ),
        migrations.DeleteModel(
            name='SalonAddress',
        ),
        migrations.DeleteModel(
            name='SalonInfo',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
